-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS counters(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR NOT NULL,
  value integer NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS counters;
-- +goose StatementEnd
