// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/mem_stats_monitoring/internal/agent/clients (interfaces: IRealIPHeaderSetter)

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRealIPHeaderSetter is a mock of IRealIPHeaderSetter interface.
type MockIRealIPHeaderSetter struct {
	ctrl     *gomock.Controller
	recorder *MockIRealIPHeaderSetterMockRecorder
}

// MockIRealIPHeaderSetterMockRecorder is the mock recorder for MockIRealIPHeaderSetter.
type MockIRealIPHeaderSetterMockRecorder struct {
	mock *MockIRealIPHeaderSetter
}

// NewMockIRealIPHeaderSetter creates a new mock instance.
func NewMockIRealIPHeaderSetter(ctrl *gomock.Controller) *MockIRealIPHeaderSetter {
	mock := &MockIRealIPHeaderSetter{ctrl: ctrl}
	mock.recorder = &MockIRealIPHeaderSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRealIPHeaderSetter) EXPECT() *MockIRealIPHeaderSetterMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockIRealIPHeaderSetter) Call(arg0 *http.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Call indicates an expected call of Call.
func (mr *MockIRealIPHeaderSetterMockRecorder) Call(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockIRealIPHeaderSetter)(nil).Call), arg0)
}
