-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS gauges(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR NOT NULL UNIQUE,
  value double precision NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS gauges;
-- +goose StatementEnd
