// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/mem_stats_monitoring/internal/server/service (interfaces: IUpdateMetricService)

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	service "github.com/vysogota0399/mem_stats_monitoring/internal/server/service"
)

// MockIUpdateMetricService is a mock of IUpdateMetricService interface.
type MockIUpdateMetricService struct {
	ctrl     *gomock.Controller
	recorder *MockIUpdateMetricServiceMockRecorder
}

// MockIUpdateMetricServiceMockRecorder is the mock recorder for MockIUpdateMetricService.
type MockIUpdateMetricServiceMockRecorder struct {
	mock *MockIUpdateMetricService
}

// NewMockIUpdateMetricService creates a new mock instance.
func NewMockIUpdateMetricService(ctrl *gomock.Controller) *MockIUpdateMetricService {
	mock := &MockIUpdateMetricService{ctrl: ctrl}
	mock.recorder = &MockIUpdateMetricServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUpdateMetricService) EXPECT() *MockIUpdateMetricServiceMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockIUpdateMetricService) Call(arg0 context.Context, arg1 service.UpdateMetricServiceParams) (service.UpdateMetricServiceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", arg0, arg1)
	ret0, _ := ret[0].(service.UpdateMetricServiceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Call indicates an expected call of Call.
func (mr *MockIUpdateMetricServiceMockRecorder) Call(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockIUpdateMetricService)(nil).Call), arg0, arg1)
}
