// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/mem_stats_monitoring/internal/server/storages (interfaces: Restorer)

// Package storages is a generated GoMock package.
package storages

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRestorer is a mock of Restorer interface.
type MockRestorer struct {
	ctrl     *gomock.Controller
	recorder *MockRestorerMockRecorder
}

// MockRestorerMockRecorder is the mock recorder for MockRestorer.
type MockRestorerMockRecorder struct {
	mock *MockRestorer
}

// NewMockRestorer creates a new mock instance.
func NewMockRestorer(ctrl *gomock.Controller) *MockRestorer {
	mock := &MockRestorer{ctrl: ctrl}
	mock.recorder = &MockRestorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestorer) EXPECT() *MockRestorerMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockRestorer) Call(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Call indicates an expected call of Call.
func (mr *MockRestorerMockRecorder) Call(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockRestorer)(nil).Call), arg0)
}
