name: multicheck

on:
  pull_request:
  push:
    branches:
      - main
      - master 

jobs: 
  multicheck:
    name: Multicheck
    runs-on: ubuntu-latest
    container: golang:1.24
    env:
      GOFLAGS: "-buildvcs=false"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build multicheck binary
        run: |
          cd cmd/staticclient
          go build -o multicheck

      - name: Run multicheck
        run: ./cmd/staticclient/multicheck ./...